### ISSUE TITLE
Automatic monthly allowance for members

### ISSUE THREAD

**Issue by cjdavis** [Hive13/MajorLazer#1]
If we decide to proceed with giving Hive members a monthly allowance of time, this would:
- Automatically add the minutes to member accounts at the beginning of the month
- Remove any remaining amount at the end of the month (if we disallow rollover)

**Comment by zombieCraig** [comment]
Funny, This seems trickier the more I think about it.  If a new member joins the hive in the middle of the month we need to automatically add time.  But if unused remove what is unused from just hat time.  Not sure if we should just do math and trust our ability to add free minutes or have special tagged minutes.  Those minutes get used up first.  That seems like he best but not easy either..hmmmm

**Comment by pvince** [comment]
Yeah, i was also thinking about this and it would be much simpler to just add 30 minutes each month.  The fact that they "expire" makes this a lot more complex.

**Comment by pvince** [comment]
A thought: We could add an "expiration" date to the minutes column or something...  When minutes are added to an account they either get a "null" expiration date which mean the time never expires, or they get a "Date" set when the minutes expire.

When calculating remaining time, you first ommit any "expired" minutes, then count up.  Could probably even make it part of the SQL query.

**Comment by zombieCraig** [comment]
If they don't expire we should give a low amount of minutes and make ppl save.  Which is a reward for staying a member I guess?

**Comment by cjdavis** [comment]
ryodoan - that's great - it would make it easy to start doing things like giving minutes to people, but they are good for a limited time.

zombiecraig - agreed. 5 - 10 minutes a month would probably be good for folks. Could even do a mix.

**Comment by reportingsjr** [comment]
AFAIK this issue has been fully implemented and works without any problems. Closing.
