### ISSUE TITLE
Ability to transfer minutes between users.

### ISSUE THREAD

**Issue by pvince** [Hive13/MajorLazer#4]
Lets say you have 50 hours worth of minutes, and you feel generous and want to give user X some of your time.

It would be nice if there was some built in way to move time from your account to another user's account.

**Comment by cjdavis** [comment]
Brilliant. +1

**Comment by zombieCraig** [comment]
Also the ability to announce you have minutes for sale?

**Comment by zombieCraig** [comment]
Or simply to beg for donation minutes.  Like a random ticker on the bottom of the homepage.  UserX would like 15 minutes, click here to donate!
